#pragma once

/**** FX data header generated by fx-data.py tool version 1.00 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfe12;
constexpr uint24_t FX_DATA_BYTES = 126246;

constexpr uint24_t World = 0x000000;
